// lection-2/react-ssi/src/pages/ProductsList.tsx
import { useEffect, useState } from "react";
import { StoreItem } from "../types";
import { navigate } from "../router";

export function ProductList({
  products: initialProducts,
}: {
  products?: StoreItem[];
}) {
  const [products, setProducts] = useState<StoreItem[] | undefined>(
    initialProducts
  );

  useEffect(() => {
    if (!products) {
      fetch("https://fakestoreapi.com/products?limit=6")
        .then((res) => res.json())
        .then(setProducts);
    }
  }, []);

  if (!products) return <p>Loading products list...</p>;

  const onClick = (event: React.MouseEvent<HTMLElement>, id: string) => {
    event.preventDefault();
    navigate(`/product/${id}`);
  };

  return (
    <div>
      <h1>Store</h1>
      <div className="products">
        {products.map((p) => (
          <div className="product" key={p.id}>
            <img src={p.image} alt={p.title} />
            <h2>{p.title}</h2>
            <p>
              <strong>${p.price}</strong>
            </p>
            <a
              href={`/product/${p.id}`}
              onClick={(event) => onClick(event, p.id)}
            >
              View
            </a>
          </div>
        ))}
      </div>
    </div>
  );
}

// lection-1/vue-ssr/src/pages/ProductsList.vue
<script setup>
import { ref, onMounted, inject } from 'vue'

const serverProducts = inject('products', null)
const products = ref(serverProducts ?? [])

onMounted(async () => {
  if (!serverProducts) {
    const res = await fetch('https://fakestoreapi.com/products?limit=6')
    products.value = await res.json()
  }
})
</script>

<template>
    <div>
      <h1>Store</h1>
      <div className="products">
        <div v-for="p in products" :key="p.id" className="product">
          <img :src="p.image" :alt=p.title />
          <h2>{{ p.title }}</h2>
          <p>
            <strong>{{ p.price }}</strong>
          </p>
          <a :href="'/product/' + p.id">View</a>
        </div>
      </div>
    </div>
</template>
