// lection-2/react-csr-app-shell/src/pages/ProductPage.tsx
import { useEffect, useState } from "react";
import { StoreItem } from "../types";
import { navigate } from "../router";

export function ProductPage({ url }: { url: URL }) {
  const id = url.pathname.split("/").at(-1);
  const [product, setProduct] = useState<StoreItem | null>(null);
  const [isProductExists, setProductExist] = useState<boolean>(true);

  useEffect(() => {
    fetch(`https://fakestoreapi.com/products/${id}`)
      .then((res) => res.json())
      .then(setProduct)
      .catch(() => setProductExist(false));
  }, [id]);

  if (!isProductExists) {
    return <p>Product does not exists!</p>
  }

  if (!product) return <p>Loading products page...</p>;

  const onClick = (event: React.MouseEvent<HTMLElement>) => {
    event.preventDefault();
    navigate('/');
  };

  return (
    <div>
      <a href="/" onClick={onClick}>← Back</a>
      <h1>{product.title}</h1>
      <img src={product.image} width="150" />
      <p>{product.description}</p>
      <p>
        <strong>${product.price}</strong>
      </p>
    </div>
  );
}

// lection-1/vue-ssr/src/pages/ProductPage.vue
<script setup>
  import { onMounted, ref, inject } from 'vue'

  const serverProducts = inject('products', null)
  const location = inject('location', null)
  const id = location.pathname.split('/').at(-1)
  const product = ref(null ?? serverProducts[id])

  onMounted(async () => {
    if (!product) {
      const res = await fetch(`https://fakestoreapi.com/products/${id}`)
      product.value = await res.json()
    }
  })
</script>

<template>
  <div v-if="product">
    <a href="/">← Back</a>
    <h1>{{ product.title }}</h1>
    <img :src="product.image" width="150" />
    <p>{{ product.description }}</p>
    <p>
      <strong>{{ product.price }}</strong>
    </p>
  </div>
</template>
